# fly.toml app configuration file generated for analytics-service-floral-sound-1237 on 2025-04-16T14:55:06-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'analytics-service-floral-sound-1237'
primary_region = 'yul'

[build]

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
